export class Datafields {
    field_id! :number;
    user_generated_id! :number;
    field_name!:string;
    field_description!:string;
    dqa_c!:string;
    commentary_a!:string;
    dqa_t!:string;
    commentary_t!:string;
    dqa_a!:string;
    commentary_c!:string;
    data_type!:string;
    field_length!:number;
    criticality!:string;
    entity_type!:string;
    entity_id!:any;
    allow_risk_update!:boolean;
    default_dqa_t!:string;
    default_dqa_a!:string;
    default_dqa_c!:string;
    default_commentary_t!:string;
    default_commentary_a!:string;
    default_commentary_c!:string;
    id!:number;
    usecaseid!:number;
    post_control_timeliness!:string;
    post_control_accuracy!:string;
    post_control_completeness!:string;
    post_control_timeliness_comment!:string;
    post_control_accuracy_comment!:string;
    post_control_completeness_comment!:string;
    control_id!:any;
}
